---
- hosts: bastion
  connection: local
  tasks:
    - name: install openshift
      import_tasks: tasks/openshift/10_install_openshift_azure.yaml
      when: platform == "azure"
    - name: install openshift
      import_tasks: tasks/openshift/10_install_openshift_roks.yaml
      when: platform == "roks"
    - name: configure openshift
      import_tasks: tasks/openshift/20_configure_openshift.yaml
    - name: configure cloudpak
      import_tasks: tasks/openshift/30_configure_cloudpak.yaml
