- name: create local directories
  file:
    path: "{{ data_dir }}/artifacts/mirror/registry"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  register: registry_offline

- name: download registry image
  shell:
    cmd: podman save docker.io/library/registry:2.6 -o {{ registry_offline.path }}/registry.tar
