- name: install packages
  become: true
  shell:
    cmd: apt install {{ data_dir}}/artifacts/packages/*.deb -y
    chdir: "{{ data_dir}}/artifacts/packages"

- name: copy docked daemon.json
  become: true
  template:
    src: templates/daemon.json.j2
    dest: "/etc/docker/daemon.json"
    force: yes

- name: enable docker on registry
  become: true
  systemd:
    name: docker
    enabled: yes
    state: restarted

- name: copy docker-compose to path
  become: true
  copy:
    src: "{{ data_dir }}/artifacts/downloads/docker-compose"
    dest: /usr/local/bin/docker-compose
    remote_src: yes
    mode: 0755

- name: extract harbor
  become: true
  unarchive:
    src: "{{ data_dir }}/artifacts/downloads/harbor-offline-installer.tgz"
    dest: "{{ data_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    remote_src: yes

- name: copy harbor configuration file
  become: true
  template:
    src: templates/harbor.yml.j2
    dest: "{{ data_dir }}/harbor/harbor.yml"
    force: yes

- name: install harbor
  become: true
  shell:
    cmd: ./install.sh --with-trivy --with-chartmuseum
    chdir: "{{ data_dir }}/harbor"

- name: update nginx configuration
  become: true
  template:
    src: templates/harbor.largerequests.conf.j2
    dest: "{{ data_dir }}/harbor/common/config/nginx/conf.d/harbor.largerequests.conf"

- name: get nginx container
  become: true
  shell:
    cmd: docker ps -q -f name=nginx
  register: nginx_container

- name: restart nginx container
  become: true
  shell:
    cmd: docker restart {{ nginx_container.stdout }}

- name: wait for nginx container
  pause:
    seconds: 15
