- name: create cluster folder
  file:
    path: "/home/{{ ansible_user }}/cluster"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: download ibmcloud cli
  get_url:
    url: https://download.clis.cloud.ibm.com/ibm-cloud-cli/{{ ibmcloud_version }}/IBM_Cloud_CLI_{{ ibmcloud_version }}_amd64.tar.gz
    dest: "/home/{{ ansible_user }}/cluster"

- name: extract ibmcloud cli
  unarchive:
    src: "/home/{{ ansible_user }}/cluster/IBM_Cloud_CLI_{{ ibmcloud_version }}_amd64.tar.gz"
    dest: "/home/{{ ansible_user }}/cluster"
    remote_src: yes

- name: authenticate with ibmcloud cli
  shell:
    cmd: |
      /home/{{ ansible_user }}/cluster/Bluemix_CLI/install
      ibmcloud plugin install container-service
      ibmcloud login --apikey {{ ibmcloud_api_key }} --no-region
      ibmcloud ks cluster config -c {{ roks_cluster_id }} --admin

